name: build and push aws

on:
  push: 
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'
        
      - name: build project
        run: dotnet restore; dotnet publish -o site;

      - name: create zip
        run: cd site; zip ../site.zip *;

      - name: deploy to aws elasticbeanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with: 
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID2 }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY2 }}
          application_name: CICD-individuell
          environment_name: CICD-individuell-env
          version_label: ${{ github.run_id }}
          region: eu-north-1
          deployment_package: site.zip